steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx', 'build',
      '--platform', 'linux/amd64',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/zergling/zergling:${_COMMIT_SHA}',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/zergling/zergling:latest',
      '.',
      '--push'
    ]

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/zergling/zergling:${_COMMIT_SHA}']

  # Create a Cloud Deploy release
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'deploy', 'releases', 'create', 'rel-${_COMMIT_SHA}',
      '--delivery-pipeline=${_PIPELINE}',
      '--region=${_REGION}',
      '--images=zergling=us-central1-docker.pkg.dev/$PROJECT_ID/zergling/zergling:${_COMMIT_SHA}',
      '--to-target=${_TARGET}'
    ]

# Store images in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/zergling/zergling:${_COMMIT_SHA}'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/zergling/zergling:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s'
