apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: zergling-pipeline                 # ← new pipeline
description: Deploy Zergling API to Cloud Run
serialPipeline:
  stages:
    - targetId: dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Deploy Zergling API to Cloud Run (dev)
run:
  location: projects/mainstreamwallstreet/locations/us-central1
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: deploy-zergling-sa@mainstreamwallstreet.iam.gserviceaccount.com
  artifactStorage: gs://us-central1.deploy-artifacts.mainstreamwallstreet.appspot.com 