substitutions:
  _REGION: us-central1
  _SERVICE: zergling-api

steps:
  # 1. Build image
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--progress=plain'
      - '-f'
      - Dockerfile
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/zergling/zergling:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/zergling/zergling:latest'
      - '.'

  # 2. Push
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/zergling/zergling:$BUILD_ID'

  # 3. Deploy to Cloud Run
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/zergling/zergling:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--concurrency=2'
      - '--timeout=300'
      - '--service-account=cloud-run-zergling-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=EXAMPLE_BUCKET=zergling-data,DEBUG=false,LOG_LEVEL=INFO'
      - '--set-secrets=ZERGLING_API_KEY=zergling-api-key:latest'
      - '--set-secrets=GOOGLE_APPLICATION_CREDENTIALS_JSON=zergling-google-sa-value:latest'

  # 4. Verify deployment
  - id: Verify
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: curl
    args:
      - '-f'
      - '-s'
      - 'https://${_SERVICE}-$PROJECT_NUMBER.${_REGION}.run.app/health'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/zergling/zergling:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/zergling/zergling:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
