apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: zergling-pipeline
spec:
  description: "Zergling API deployment pipeline"
  serialPipeline:
    stages:
      - targetId: dev
        profiles: []
        strategy:
          standard:
            verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
spec:
  description: "Development environment"
  requireApproval: false
  executionConfigs:
    - usages:
        - RENDER
        - DEPLOY
      serviceAccount: deploy-zergling-sa@mainstreamwallstreet.iam.gserviceaccount.com
      artifactStorage: gs://us-central1.deploy-artifacts.mainstreamwallstreet.appspot.com
      executionTimeout: 3600s
  run:
    location: us-central1 