substitutions:
  _REGION: us-central1
  _SERVICE: archon-content-api
  _LANGFLOW_SERVER_URL: https://langflow-455624753981.us-central1.run.app/api/v1/run/

steps:
  # 1. Build image
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--progress=plain'
      - '--cache-from=${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:latest'
      - '-f'
      - Dockerfile
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:$BUILD_ID'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:latest'
      - '.'

  # 2. Push image
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:$BUILD_ID'
    waitFor: ['Build']

  # 3. Deploy to Cloud Run
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--concurrency=2'
      - '--timeout=300'
      - '--service-account=cloud-run-archon-content-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=EXAMPLE_BUCKET=zergling-data,DEBUG=false,LOG_LEVEL=INFO,LANGFLOW_SERVER_URL=${_LANGFLOW_SERVER_URL}'
      - '--set-secrets=ARCHON_API_KEY=archon-api-key:latest'
      - '--set-secrets=GOOGLE_APPLICATION_CREDENTIALS_JSON=archon-google-sa-value:latest'
      - '--set-secrets=LANGFLOW_API_KEY=langflow-api-key:latest'
    waitFor: ['Push']

  # 4. Verify deployment
  - id: Verify
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "🏥 Verifying deployment..."
        sleep 30
        MAX_RETRIES=10
        RETRY_COUNT=0
        
        while [ $$RETRY_COUNT -lt $$MAX_RETRIES ]; do
          if curl -f -s "https://${_SERVICE}-$PROJECT_NUMBER.${_REGION}.run.app/health" > /dev/null; then
            echo "✅ Health check passed!"
            break
          else
            echo "   Health check failed (attempt $$((RETRY_COUNT + 1))/$$MAX_RETRIES)"
            RETRY_COUNT=$$((RETRY_COUNT + 1))
            if [ $$RETRY_COUNT -eq $$MAX_RETRIES ]; then
              echo "❌ Health check failed after $$MAX_RETRIES attempts"
              exit 1
            fi
            sleep 10
          fi
        done
    waitFor: ['Deploy']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/archon-content/archon-content:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
