substitutions:
  _REGION: us-central1
  _PIPELINE: ffs-pipeline

steps:
  # 1. Build image
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--progress=plain'
      - '-f'
      - Dockerfile
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/filing-fetcher-api/filing-fetcher-api:$BUILD_ID'
      - '.'

  # 2. Push
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/filing-fetcher-api/filing-fetcher-api:$BUILD_ID'

  # 3. Cloud Deploy release
  - id: Release
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - 'rel-$BUILD_ID'
      - '--delivery-pipeline=${_PIPELINE}'
      - '--region=${_REGION}'
      - '--images=api-image=${_REGION}-docker.pkg.dev/$PROJECT_ID/filing-fetcher-api/filing-fetcher-api:$BUILD_ID'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/filing-fetcher-api/filing-fetcher-api:$BUILD_ID'

timeout: '900s'
