apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Deploy FFS API to Cloud Run (dev)
run:
  location: projects/mainstreamwallstreet/locations/us-central1
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: deploy-ffs-sa@mainstreamwallstreet.iam.gserviceaccount.com
