apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: zergling-pipeline                 # ← new pipeline
description: Promote Zergling API to Cloud Run
serialPipeline:
  stages:
    - targetId: dev
