name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Authenticate first
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

      # OPTIONAL debug – now the token exists
      - name: Show repo claim
        run: |
          echo "OIDC repository claim: $(echo "$ACTIONS_ID_TOKEN" | cut -d'.' -f2 | base64 -d | jq -r .repository)"
        env:
          ACTIONS_ID_TOKEN: ${{ steps.auth.outputs.id_token }}

      # Install gcloud & set project
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Submit Cloud Build
        run: |
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions=_REGION=us-central1,_PIPELINE=banshee-pipeline,_SERVICE=api
