name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FFS_API_KEY:                 ${{ secrets.FFS_API_KEY }}
      TOKEN:                       ${{ secrets.TOKEN }}
      GOOGLE_DRIVE_ROOT_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER_ID }}
      OPENAI_API_KEY:              "dummy"
      API_NINJAS_KEY:              "dummy"
      JOB_QUEUE_BUCKET:            "test-bucket"  # Using test bucket name for mocked GCS

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v
