name: PR Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, feature/cloud-deploy-pipeline]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    permissions:
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
        working-directory: ${{ github.workspace }}

      - name: Run pre-commit checks (Black, flake8)
        run: pre-commit run --all-files
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing
        working-directory: ${{ github.workspace }}
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false 