name: Test Trigger

on:
  push:
    branches: [feature/cloud-deploy-pipeline]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        run: |
          echo "GitHub Actions are working!"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}" 